name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        bundler-cache: true
        ruby-version: "2.7.2"
    - run: gem install bundler:1.17.3
    - run: bundle install
    - run: bundle exec middleman build
    - if: ${{ github.repository_owner == 'scalikejdbc' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: ./build
        CLEAN: true
