name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
      with:
        bundler-cache: true
        ruby-version: "2.7.2"
    - run: gem install bundler:1.17.3
    - run: bundle install
    - run: bundle exec middleman build
    - if: ${{ github.repository_owner == 'scalikejdbc' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: ./build
        CLEAN: true
