name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
      with:
        bundler-cache: true
        ruby-version: "2.7.2"
    - run: gem install bundler:1.17.3
    - run: bundle install
    - run: bundle exec middleman build
    - if: ${{ github.repository_owner == 'scalikejdbc' && github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: ./build
        CLEAN: true
